name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Railway
        uses: railwayapp/railway-action@master
        with:
          railwayToken: ${{ secrets.RAILWAY_API_KEY }}
